### ISSUE TITLE
I am more interested in the implementation details of InjectionLoader, do you plan to open the source code ?

### ISSUE THREAD

**Issue by arronttxx** [johnno1962/InjectionScratch#1]

**Comment by johnno1962** [comment]
Hi, there isn't much to it. It's mostly about pretending to be the dynamic linker which I use the modified version of fishhook in SwiftTrace for. The dylib is relocated using the linker -image_base option and simply read into memory after it is switched from executable to read/write then the text segment made executable again using mprotect(). I may Open Source it later in the year depending on how useful it is.

**Comment by johnno1962** [comment]
I brought the InjectionLoader source into this repo if you're still interested.
